### PR TITLE
Removing oldunittests

### PR DESCRIPTION
**Pull request by apurvabanka**
### **User description**
Linked Issue #350

___

### **PR Type**
Tests

___

### **Description**
- Removed `oldunit_test.py` which contained outdated unit tests.
- Added a new test `test_subelement_bool_kwarg` in `helper_test.py` to test boolean subelement keyword arguments.
- Enhanced `features_test.py` by adding an assertion to check the truthiness of `network_link.snippet`.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Tests</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>features_test.py</strong><dd><code>Add assertion for snippet truthiness in network link test</code></dd></summary>
<hr>

tests/features_test.py

- Added an assertion to check if `network_link.snippet` is truthy.

</details>

  </td>
  <td><a href="https://github.com/cleder/fastkml/pull/370/files#diff-7621b636c4d6f9c35732eaf1342d5e73d4247d53b6d617dfc424e2477f6f2944">+1/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>helper_test.py</strong><dd><code>Add test for subelement boolean keyword argument</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/helper_test.py

<li>Imported <code>subelement_bool_kwarg</code> from <code>fastkml.helpers</code>.<br> <li> Added a new test <code>test_subelement_bool_kwarg</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/cleder/fastkml/pull/370/files#diff-dc75202fca02900edc2cf6259c9caeb0f3ae69b6593e13be25f6301610921d53">+19/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>oldunit_test.py</strong><dd><code>Remove old unit tests file</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

tests/oldunit_test.py

- Removed the entire file containing old unit tests.

</details>

  </td>
  <td><a href="https://github.com/cleder/fastkml/pull/370/files#diff-20b895a94d083ca050b74044b0167d1d3234fe31d0d177d144085b9359118899">+0/-1141</a></td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

## Summary by CodeRabbit

- **Tests**
	- Added a new assertion in the `test_network_link_read` method to validate the `snippet` attribute of `NetworkLink`.
	- Introduced a new test method `test_subelement_bool_kwarg` to verify the functionality of `subelement_bool_kwarg`.
	- Added a new class `TestKmlFromString` with multiple test methods for parsing various KML structures.
	- Added a new class `TestStyleUsage` with methods to test the creation of KML documents and placemarks with styles.
	- Removed the `tests/oldunit_test.py` file, which contained extensive KML handling tests.

### CODE REVIEW

**Comment by apurvabanka** [comment]
@cleder Can you change the base branch for this PR?

**Comment by cleder** [comment]
Which removed tests did test the lines that were not covered after removing the old_unittests? Why weren't they kept, and new tests introduced instead?

**Comment by apurvabanka** [comment]
> Which removed tests did test the lines that were not covered after removing the old_unittests? Why weren't they kept, and new tests introduced instead?

There were difference in coverage in 2 files - fastkml/feature.py and fastkml/helper.py. 
For helper.py below lines of code were not present in coverage. 

https://github.com/cleder/fastkml/blob/ed01d625d9985b8e7a019f56fbab283903650618/fastkml/helpers.py#L634-L650

So, added a test case for those.
For feature.py there was only 1 line of code that was not present in the coverge.

https://github.com/cleder/fastkml/blob/ed01d625d9985b8e7a019f56fbab283903650618/fastkml/features.py#L165

Modified a test case to cover the same. Let me know if I missed something.

**Comment by cleder** [comment]
In addition to the new tests, I would like to keep the tests that covered those lines in the first place. Just exercising the code without a use case is not enough.

**Comment by apurvabanka** [comment]
> In addition to the new tests, I would like to keep the tests that covered those lines in the first place. Just exercising the code without a use case is not enough.

Apologies for the mis-understanding. I investigated all the tests in the oldunittest.py. There were 2 classes that were responsible for decrease in coverage - TestKmlFromString, TestStyleUsage. I have moved those tests to the respective new test file making sure there is no duplication for the tests. Please proceed with the review.

**Review by cleder — APPROVED** [review]

**Pull request merged**
