### PR TITLE
 Bandit Error B101 : assert_used

### PR DESCRIPTION
**Pull request by withoutwaxaryan**
Bandit is a tool designed to find common security issues in Python code.

Solves Error B101 ; assert_used --> "Use of assert detected. The enclosed code will be removed when compiling to optimised byte code."

### CODE REVIEW

**Comment by withoutwaxaryan** [comment]
Retry DeepCode

**Comment by cleder** [comment]
Hi,
Thanks for your great work in the GSOC :-)

**Comment by withoutwaxaryan** [comment]
Thank you!!

**Comment by withoutwaxaryan** [comment]
Hi @cleder , 
Sorry for the delay in my reply. I did not get the notification to rebase the PR. I'll do that :))

Also, I would love to be a maintainer! What responsibilities would that comprise of ?

**Comment by withoutwaxaryan** [comment]
@cleder , I am facing some problems. Do guide me :))
I tried switching the base branch from cleder:master to cleder:develop. But it started showing extra commits from other people. 

I think the problem is that I had forked the stable branch and now Im making a PR on the develop branch.
How should I proceed?

**Pull request closed without merging**
