### PR TITLE
raise error for 'No geometries found' case

### PR DESCRIPTION
**Pull request by hyperknot**

### CODE REVIEW

**Comment by cleder** [comment]
The tests do not pass, 3 Errors. also there are no tests for the new functionality

**Comment by cleder** [comment]
mak the test pass and I'll merge it ;-)

**Comment by hyperknot** [comment]
OK, I thought you are against the change for the architecture of fastkml by introducing a Raise there. If you are ok, I'll look at the test and modify the PR.

**Comment by cleder** [comment]
I think it should be a more specific Error should be raised, like NoGeometriesFoundError (which can be subclassed from ValueError), so it can be caught by the user and handled at application level.

**Pull request closed without merging**
