### PR TITLE
raise error and debug log for no geometries found case

### PR DESCRIPTION
**Pull request by hyperknot**

### CODE REVIEW

**Comment by hyperknot** [comment]
OK, so I redid this PR as you said you would be interested in merging it. The reason for this PR is that it'd be important to detect if a geometry is not recognised, so I can preprocess the file in GPSBabel for example. One such case is the not yet supported gxTracks format, which GPSBabel can convert to normal lines and thus make it compatible with fastkml.

The problem is that it breaks 3 tests and I don't know what do you think would be the best way to fix them. Some users might want to raise exceptions some might prefer to skip that geometry silently. 

I think the only clean solution here is to introduce a parameter for KML() or from_string() about raising exceptions / skipping silently. What do you think?

**Comment by heltonbiker** [comment]
I would like to present an use-case (that is, from a User perspective):

### Use Case
> As an user of a Map viewer/editor program using `fastkml`;
> I want to open a KML file in such program, edit it and save it back without losing any pre-existing tags;
> So that I can be sure any hand-inserted element tags would not be lost inadvertently;

### Acceptance Test(s)
> Given a file with invalid or unrecognized xml data;
> When I open the file with fastkml, optionally edit its parsed content, and save it back;
> Then any unrecognized content would be preserved in the written xml.

That is: if `gx:Track` is recognized, it should be written back as a `gx:Track`. If it's not, it should be left untouched.

I think it _should not_ be converted to something else implicitly.

I think it _might_ be converted to another geometry explicitly.

**Comment by hyperknot** [comment]
OK, how would you like to change fastkml for that? At the moment, if there is a gx:Track, it is silently skipped, I believe.

**Comment by heltonbiker** [comment]
Well, that's a good question. As a newcomer, I am not sure what the answer should be, so I would rather wait for the opinion of more senior contributors. Some factors I would consider:

- Parsing is parsing, and conversion is conversion. Parsing should not be responsible by (or even allowed to) performing conversions.
- There is a difference in _not recognized_ and _not yet implemented_.
- The current problem is not caused by anything else than an element that _should_ be recognized not being so _yet_. As such, the actual solution would be to implement `gx:Track`.

While `gx:Track` is not implemented, I think we should have two tests (given below with mock names), with the specific goal to differentiate between "unrecognized" and "absent" situations:

1. The `TrackIsIgnored()` test should silently ignore a `gx:Track`, while still writing it back to output untouched;
2. The `EmptyGeometryRaisesError` should raise a proper error.

These are my impressions, I'm not sure about them. Any opinions?

**Comment by heltonbiker** [comment]
I had another idea:
What if the whole Placemark element containing the `gx:Track` is silently ignored?
I mean, since the whole point of having a Placemark is to refer to its geometry, and if `fastkml` currently does not implement a given geometry, it shouldn't even load its Placemark at all.

Does that make sense? Would this be possible to implement, currently?

Proposed test:

- Given a KML string containing Placemark, where each Placemark contains one different type of geometry (Point, LineString, LinearRing, Polygon, MultiGeometry, Model, gx:Track);
- When the KML is loaded by `fastkml`;
- All Placemarks are successfully loaded, _except_ the one containing `gx:Track`, which is silently ignored as a whole.

**Comment by cleder** [comment]
@hyperknot Did you add your name to the contributors.txt ?

**Comment by hyperknot** [comment]
@cleder thanks, I've just added. What would be the best solution for configuring exception behaviour to raise / silently skip? At the moment it silently skips, so it should be the default. I think the best option would be to add a raise_error=False to either:
`KML / def __init__(self, ns=None, raise_error=False):`
or
`KML / def from_string(self, xml_string, raise_error=False):`

Adding it to the KML object would make this behaviour global on an object level, so wouldn't need to be passed onto sub-functions like `feature.from_element(document, raise_error=False)`, etc.

**Comment by cleder** [comment]
I do not think that a `raise_error` would be beneficial.
I think it rather should be a more specific Error should be raised, like NoGeometriesFoundError (which can be subclassed from ValueError), so it can be caught by the user and handled at application level.

**Comment by hyperknot** [comment]
OK, implementing a NoGeometriesFoundError for this case is straightforward, and it would be fitting for my use case (which is detecting if there are wrong geometries and running a GPSBabel pre-processing step if needed).

However there might be other users who would prefer to silently skip wrong placemarks. For example you have 99 waypoints and 1 gxTrack, and those users might want to import the 99 waypoints even if the 1 gxTrack has to be skipped. If we raise anything there, the whole import is terminated, not just that single placemark. Trying to catch that exception won't be any help, since it would still terminate the import process.

I am open for your suggestion, what would be the best in this case.

**Comment by heltonbiker** [comment]
I would like to suggest something.
The library SharpKml has the concept of "orphan", that is, "_an invalid XML element to be stored for later (re)serialization_".

So, their idea, which I believe is the Right Thing, is to "objectify" the recognized elements and present them to the application as usual, but to store the unrecognized ones "as is" for later serialization.

One downside is the behaviour desired by @hyperknot (involving GpsBabel) would be harder to achieve from within fastkml, if possible at all.

Their class `Element.cs` is, (just the relevant parts)

    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Linq;
    using System.Text;
    using System.Xml;
    using SharpKml.Base;

    namespace SharpKml.Dom
    {
        public abstract class Element
        {
            private List<XmlComponent> _attributes = new List<XmlComponent>();
            private List<Element> _children = new List<Element>();
            private Dictionary<Type, int> _childTypes = new Dictionary<Type, int>();
            private List<Element> _orphans = new List<Element>();   //////////////////////////////
            private StringBuilder _text = new StringBuilder();

            protected Element()
            {
                this.Children = new ReadOnlyCollection<Element>(_children);
                this.Namespaces = new XmlNamespaceManager(new NameTable());
            }

            /// (...)

            /// <summary>Gets invalid child Elements found during parsing.</summary>
            internal IEnumerable<Element> Orphans
            {
                get { return _orphans; }
            }

            /// (...)

            /// <summary>
            /// Stores an invalid child Element for later serialization.
            /// </summary>
            /// <param name="orphan">The Element to store for serialization.</param>
            protected internal virtual void AddOrphan(Element orphan)
            {
                if (orphan != null)
                {
                    orphan.Parent = this;
                    _orphans.Add(orphan);
                }
            }

            /// (...)
        }
    }

**Comment by hyperknot** [comment]
@heltonbiker I don't think there is any point in keeping the broken placemark. It should either be recognised or skipped, how would you map a non-recognised geometry to a shapely object for example?

**Comment by heltonbiker** [comment]
@hyperknot , I am thinking about the more generic case of a non recognized _element_ in the XML structure, which should be "left alone" and serialized back.

For example, if I do this (pseudocode):

    model = fastkml.open('file_with_gxTrack.kml")
    editSomehow(model)
    model.saveBack('copy.kml')

I would be very [surprised](http://programmers.stackexchange.com/questions/187457/what-is-the-principle-of-least-astonishment) to find out the existing `gx:Tracks` were (silently?) converted to something else (by GpsBabel in your use case).

**Pull request merged**
