### PR TITLE
Revert "raise error and debug log for no geometries found case"

### PR DESCRIPTION
**Pull request by cleder**
Reverts cleder/fastkml#44

### CODE REVIEW

**Comment by heltonbiker** [comment]
So what happens when no geometry is found? In my opinion, a Placemark without a geometry should not be considered a valid placemark (and thus should not be included in the parsed KML tree, being left "as is" in the file).

I propose to do something like this (pseudocode):

<pre>
try:
    placemarkObject = parsePlacemark(node)
    tree.append(placemarkObject)
except GeometryNotFound:
    log.warn(message)
</pre>

That way, the creation of the full Placemark would be "rolled back" if it doesn't contain valid values for all its required properties.

**Comment by cleder** [comment]
I am just waiting for the tests to be fixed, than your PR goes back in ;-)

**Comment by heltonbiker** [comment]
Actually it's @hyperknot PR :o)

**Comment by hyperknot** [comment]
@cleder I need your input for how to change this behaviour. We need to specify if we want to raise an error or silently skip it. I've explained it here:
https://github.com/cleder/fastkml/pull/44#issuecomment-217114105

**Pull request closed without merging**
